services:
  mircs:
    build: .
    # restart: always
    environment:
      - PORT=80
      - MONGO_SERVER_URL=mongodb://mongoadmin:secret@mongo
    ports:
      - 8080:80

  mongo:
    image: mongo:5.0.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
